### ISSUE TITLE
Chef 13 deprecation warnings

### ISSUE THREAD

**Issue by mfischer-zd** [chef-cookbooks/yum-repoforge#12]
### Cookbook version
0.7.0

### Chef-client version
Chef 12.12.15

### Summary
```
"method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 3 locations:
- /tmp/kitchen/cache/cookbooks/yum-repoforge/attributes/rpmforge-extras.rb:3:in `from_file'
- /tmp/kitchen/cache/cookbooks/yum-repoforge/attributes/rpmforge-testing.rb:3:in `from_file'
- /tmp/kitchen/cache/cookbooks/yum-repoforge/attributes/rpmforge.rb:3:in `from_file'
```

**Comment by iennae** [comment]
Resolved with the latest release version 0.7.1 of the cookbook.
